### ISSUE TITLE
0.2 release checklist

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#1319]
TODO (is 0.2 the next number? the last one was 0.1.2)
- see the [0.2 milestone](https://github.com/popsim-consortium/stdpopsim/milestone/4)

**Comment by jeromekelleher** [comment]
0.2 seems right - I guess we can then plan for 0.3 as the version that converts the demographic models in the catalog to demes (with some code breakage, probably)?

**Comment by nspope** [comment]
- [ ] make sure you're on main
- [ ] increment the version in _version.py [NP: doesn't exist?]
- [ ] update CHANGELOG
- [ ] commit and tag
- [ ] update tags on github with `git push; git push --tags`
- [ ] upload to pypi:
```
python3 setup.py sdist bdist_wheel
twine upload dist/FILES_TO_UPLOAD
```
- [ ] check on pypi that the update actually worked
- [ ] check docs build succeeded
- [ ] upload to zenodo
- [ ] update version and DOI in CITATION.cff (once added)
- [ ] conda-forge will do an automatic PR; winni2k says:
> "The key things I checked were that the version number is correct, the SHA sum has changed, and that the build number is reset to zero. Any other problems should be caught by the automated build system."

Post-release:
- [ ] make copy of this issue for the next release

Reference: https://packaging.python.org/tutorials/packaging-projects/, https://github.com/tskit-dev/pyslim/issues/292

**Comment by grahamgower** [comment]
> * [ ]  make sure you're on main
> * [ ]  increment the version in _version.py [NP: doesn't exist?]
> * [ ]  update CHANGELOG
> * [ ]  commit and tag
> * [ ]  update tags on github with `git push; git push --tags`
> * [ ]  upload to pypi:
> 

FYI, stdpopsim is using `setuptools_scm` to determine the version. So, when you build the package with something like `python setup.py build` (or using non-deprecated build tools `pip install build; python -m build`), then the `stdpopsim/_version.py` file will be created. This means you need to create the tag, then build, before the appropriate version will be visible.

Also, we should change from using setup.py to using pyproject.toml and setup.cfg, following current best practices for Python packages (setup.py is deprecated).

**Comment by grahamgower** [comment]
> * python3 -m twine upload [stuff]

You're still uploading to pypi manually, like a barbarian? :P

**Comment by jeromekelleher** [comment]
Adds the personal touch for grass-fed artisanal packages

**Comment by petrelharp** [comment]
We have done this.
